import DOMPurify from "dompurify";
import { formatQuotedDate } from "shared/dates";
import type { Attachment } from "~/types";
export { formatListDate, formatDetailDate, formatShortDate } from "shared/dates";
export const formatComposeDate=formatQuotedDate;
export function formatBytes(bytes:number,decimals=1){if(bytes===0)return "0 B";const k=1024,dm=decimals<0?0:decimals,sizes=["B","KB","MB","GB"],i=Math.floor(Math.log(bytes)/Math.log(k));return `${Number.parseFloat((bytes/Math.pow(k,i)).toFixed(dm))} ${sizes[i]}`;}
export function splitEmailList(value?:string|null):string[]{return(value||"").split(",").map(e=>e.trim()).filter(Boolean);}
export function toEmailListValue(addresses:string[]):string|string[]|undefined{return addresses.length===0?undefined:addresses.length===1?addresses[0]:addresses;}
export function htmlToPlainText(html:string):string{const sanitized=DOMPurify.sanitize(html);const div=document.createElement("div");div.innerHTML=sanitized.replace(/<style[^>]*>[\s\S]*?<\/style>/gi,"").replace(/<br\s*\/?>/gi,"\n").replace(/<\/p>/gi,"\n\n").replace(/<p[^>]*>/gi,"").replace(/<div[^>]*>/gi,"").replace(/<\/div>/gi,"\n");return(div.textContent||div.innerText||"").trim();}
export function stripHtml(html:string):string{return html.replace(/<[^>]*>/g,"").replace(/\s+/g," ").trim();}
function decodeHtmlEntities(text:string){return text.replace(/&#(\d+);/g,(_m,c)=>String.fromCharCode(Number(c))).replace(/&#x([0-9a-f]+);/gi,(_m,h)=>String.fromCharCode(Number.parseInt(h,16))).replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&apos;/g,"'").replace(/&nbsp;/g," ");}
export function getSnippetText(snippet?:string|null,maxLength=100){if(!snippet)return "";const clean=decodeHtmlEntities(snippet.replace(/<style[^>]*>[\s\S]*?<\/style>/gi,"").replace(/<style[^>]*>[\s\S]*/gi,"").replace(/<[^>]*>/g," ").replace(/<[^>]*$/g,"")).replace(/\s+/g," ").trim();return clean?clean.length>maxLength?`${clean.slice(0,maxLength)}...`:clean:"";}
export function escapeHtml(text:string){return text?text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;"):"";}
type SignatureInlineImage={url:string;alt:string;cid?:string;label?:string};
function signatureAssetHtml(a:SignatureInlineImage){const label=a.label??(a.alt.toLowerCase().includes("whatsapp")?"WhatsApp":a.alt.toLowerCase().includes("telegram")?"Telegram":"");const image=a.cid?`<img src="${a.url}" data-cid="${escapeHtml(a.cid)}" width="64" height="64" alt="${escapeHtml(a.alt)}" style="display:block;width:64px;height:64px;max-width:64px;max-height:64px;object-fit:contain;margin:0 auto;" />`:`<img src="${a.url}" alt="${escapeHtml(a.alt)}" style="display:block;max-height:80px;max-width:120px;object-fit:contain;margin:0 auto;" />`;return label?`<span data-signature-asset="social" data-signature-label="${escapeHtml(label)}" style="display:inline-block;vertical-align:top;width:96px;margin:0 32px 0 0;padding:0;text-align:center;line-height:1.2;white-space:nowrap;">${image}<span style="display:block;font-size:11px;line-height:16px;margin-top:4px;text-align:center;white-space:nowrap;">${escapeHtml(label)}</span></span>`:`<span data-signature-asset="logo" style="display:inline-block;vertical-align:top;width:140px;margin:0 32px 0 0;padding:0;text-align:center;line-height:0;white-space:nowrap;">${image}</span>`;}
export function getSignatureBlock(settings?:{signature?:{enabled:boolean;text?:string;html?:string;logoDataUrl?:string;logoKey?:string}},mailboxId?:string,inlineImages:SignatureInlineImage[]=[]):string{const sig=settings?.signature;if(!sig?.enabled)return "";let content=sig.html?DOMPurify.sanitize(sig.html):escapeHtml(sig.text||"");content=content.replace(/(<strong>Telegram:<\/strong>\s*)(https?:\/\/[^\s<]+|t\.me\/[^\s<]+|@[A-Za-z0-9_]+)/gi,(_m,prefix,value)=>{const href=value.startsWith("http://")||value.startsWith("https://")?value:`https://${value.startsWith("@")?`t.me/${value.slice(1)}`:value}`;return `${prefix}<a href="${escapeHtml(href)}">${escapeHtml(value)}</a>`;});content=DOMPurify.sanitize(content);const assets:SignatureInlineImage[]=[...inlineImages];if(sig.logoKey&&mailboxId)assets.unshift({url:`/api/v1/mailboxes/${encodeURIComponent(mailboxId)}/signature-logo`,alt:"Company logo"});else if(sig.logoDataUrl?.startsWith("data:image/"))assets.unshift({url:sig.logoDataUrl,alt:"Company logo"});const assetsHtml=assets.length?`<p data-signature-row="true" style="margin:10px 0 0;padding:0;line-height:normal;white-space:nowrap;display:block;">${assets.map(signatureAssetHtml).join("")}</p>`:"";return `<div style="border-top:1px solid #ccc;margin-top:16px;padding-top:12px;">${content}${assetsHtml}</div>`;}
export function buildQuotedReplyBlock(dateStr:string|undefined,sender:string,body:string){if(!body)return "";const plainBody=htmlToPlainText(body);return `<br><blockquote style="border-left:2px solid #ccc;margin:0;padding-left:1em;color:#666;">On ${formatComposeDate(dateStr)}, ${escapeHtml(sender)} wrote:<br><br>${escapeHtml(plainBody).replace(/\n/g,"<br>")}</blockquote>`;}
export function rewriteInlineImages(body:string,mailboxId:string,emailId:string,attachments?:{id:string;content_id?:string|null;disposition?:string|null}[]){if(!body||!attachments?.length)return body;let result=body;for(const att of attachments){if(!att.content_id)continue;const cid=att.content_id.replace(/^<|>$/g,"").trim();if(!cid)continue;const relativeUrl=`/api/v1/mailboxes/${encodeURIComponent(mailboxId)}/emails/${encodeURIComponent(emailId)}/attachments/${encodeURIComponent(att.id)}`;const url=typeof window!=="undefined"?new URL(relativeUrl,window.location.origin).href:relativeUrl;const escapedCid=cid.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");result=result.replace(new RegExp(`cid:\\s*<?${escapedCid}>?`,"gi"),url);}return result;}
export function getNonInlineAttachments(attachments?:Attachment[]):Attachment[]{return attachments?.filter(a=>a.disposition!=="inline")??[];}
export function getAttachmentUrl(mailboxId:string,emailId:string,attachmentId:string){return `/api/v1/mailboxes/${encodeURIComponent(mailboxId)}/emails/${encodeURIComponent(emailId)}/attachments/${encodeURIComponent(attachmentId)}`;}
export function downloadFile(url:string,filename:string){const link=document.createElement("a");link.href=url;link.download=filename;link.target="_blank";link.rel="noopener noreferrer";document.body.appendChild(link);link.click();document.body.removeChild(link);}
