import { Badge, Button, Input, Loader, useKumoToastManager } from "@cloudflare/kumo";
import { RobotIcon, ArrowCounterClockwiseIcon, PaperPlaneTiltIcon, TelegramLogoIcon, ImageIcon } from "@phosphor-icons/react";
import { useEffect, useState } from "react";
import { useParams } from "react-router";
import { useMailbox, useUpdateMailbox } from "~/queries/mailboxes";
import api from "~/services/api";
const PROMPT_PLACEHOLDER=`You are an email assistant that helps manage this inbox. You read emails, draft replies, and help organize conversations.\n\nWrite like a real person. Short, direct, flowing prose. Plain text only.\n\n(Leave empty to use the full built-in default prompt)`;
const DEFAULT_SIGNATURE="<div><strong>Gavin Gwynn</strong><br><strong>Whatsapp:</strong> @Gavin.Gwynn<br><strong>Telegram:</strong> <a href=\"https://t.me/Gavin_Gwynn99\">https://t.me/Gavin_Gwynn99</a><br><br><strong>Astra International (HK) Trade Limited</strong></div>";
export default function SettingsRoute(){
 const{mailboxId}=useParams<{mailboxId:string}>();const toast=useKumoToastManager();const{data:mailbox}=useMailbox(mailboxId);const update=useUpdateMailbox();
 const[displayName,setDisplayName]=useState("");const[agentPrompt,setAgentPrompt]=useState("");const[forwardEnabled,setForwardEnabled]=useState(false);const[forwardEmail,setForwardEmail]=useState("");const[forwardInternal,setForwardInternal]=useState(true);const[telegramEnabled,setTelegramEnabled]=useState(false);const[telegramToken,setTelegramToken]=useState("");const[telegramChatId,setTelegramChatId]=useState("");const[telegramInternal,setTelegramInternal]=useState(true);const[signatureEnabled,setSignatureEnabled]=useState(false);const[signatureHtml,setSignatureHtml]=useState("");const[logoKey,setLogoKey]=useState("");const[logoVersion,setLogoVersion]=useState(0);const[isSaving,setIsSaving]=useState(false);const[isUploading,setIsUploading]=useState(false);
 useEffect(()=>{if(!mailbox)return;const s=mailbox.settings||{};setDisplayName(s.fromName||mailbox.name||"");setAgentPrompt(s.agentSystemPrompt||"");setForwardEnabled(s.forwarding?.enabled===true);setForwardEmail(s.forwarding?.email||"");setForwardInternal(s.forwarding?.includeInternal!==false);setTelegramEnabled(s.telegram?.enabled===true);setTelegramToken(s.telegram?.botToken||"");setTelegramChatId(s.telegram?.chatId||"");setTelegramInternal(s.telegram?.includeInternal!==false);setSignatureEnabled(s.signature?.enabled===true);setSignatureHtml(s.signature?.html||s.signature?.text||"");setLogoKey(s.signature?.logoKey||"");setLogoVersion(Date.now());},[mailbox]);
 const logoUrl=mailboxId&&logoKey?`/api/v1/mailboxes/${encodeURIComponent(mailboxId)}/signature-logo?v=${logoVersion}`:"";
 const handleLogo=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.currentTarget.value="";if(!file||!mailboxId||!mailbox)return;if(!["image/png","image/jpeg","image/gif","image/webp"].includes(file.type)){toast.add({title:"Please select a PNG, JPEG, GIF or WebP image",variant:"error"});return;}if(file.size>500*1024){toast.add({title:"Logo must be smaller than 500 KB",variant:"error"});return;}setIsUploading(true);try{const result=await api.uploadSignatureLogo(mailboxId,file);const next={...mailbox.settings,signature:{...mailbox.settings?.signature,enabled:signatureEnabled,html:signatureHtml.trim()||DEFAULT_SIGNATURE,logoKey:result.key,logoDataUrl:undefined}};await update.mutateAsync({mailboxId,settings:next});setLogoKey(result.key);setLogoVersion(Date.now());toast.add({title:"Company logo uploaded to R2"});}catch(e){toast.add({title:e instanceof Error?e.message:"Failed to upload logo",variant:"error"});}finally{setIsUploading(false);}};
 const removeLogo=async()=>{if(!mailboxId)return;try{await api.deleteSignatureLogo(mailboxId);setLogoKey("");setLogoVersion(Date.now());toast.add({title:"Company logo removed"});}catch(e){toast.add({title:e instanceof Error?e.message:"Failed to remove logo",variant:"error"});}};
 const handleSave=async()=>{if(!mailbox||!mailboxId)return;if(forwardEnabled&&!forwardEmail.trim()){toast.add({title:"Enter a forwarding email address",variant:"error"});return;}if(telegramEnabled&&(!telegramToken.trim()||!telegramChatId.trim())){toast.add({title:"Enter the Telegram Bot Token and Chat ID",variant:"error"});return;}setIsSaving(true);const settings={...mailbox.settings,fromName:displayName,agentSystemPrompt:agentPrompt.trim()||undefined,forwarding:{...mailbox.settings?.forwarding,enabled:forwardEnabled,email:forwardEmail.trim().toLowerCase(),includeInternal:forwardInternal},telegram:{...mailbox.settings?.telegram,enabled:telegramEnabled,botToken:telegramToken.trim(),chatId:telegramChatId.trim(),includeInternal:telegramInternal},signature:{...mailbox.settings?.signature,enabled:signatureEnabled,html:signatureHtml.trim()||DEFAULT_SIGNATURE,logoKey:logoKey||undefined,logoDataUrl:undefined}};try{await update.mutateAsync({mailboxId,settings});toast.add({title:"Settings saved!"});}catch{toast.add({title:"Failed to save settings",variant:"error"});}finally{setIsSaving(false);}};
 if(!mailbox)return <div className="flex justify-center py-20"><Loader size="lg"/></div>;const custom=agentPrompt.trim().length>0;
 return <div className="max-w-2xl px-4 py-4 md:px-8 md:py-6 h-full overflow-y-auto"><h1 className="text-lg font-semibold text-kumo-default mb-6">Settings</h1><div className="space-y-6">
  <div className="rounded-lg border border-kumo-line bg-kumo-base p-5"><div className="text-sm font-medium mb-4">Account</div><div className="space-y-3"><Input label="Display Name" value={displayName} onChange={e=>setDisplayName(e.target.value)}/><Input label="Email" type="email" value={mailbox.email} disabled/></div></div>
  <div className="rounded-lg border border-kumo-line bg-kumo-base p-5"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><RobotIcon size={16}/><span className="text-sm font-medium">AI Agent Prompt</span>{custom?<Badge variant="primary">Custom</Badge>:<Badge variant="secondary">Default</Badge>}</div>{custom&&<Button variant="ghost" size="xs" icon={<ArrowCounterClockwiseIcon size={14}/>} onClick={()=>setAgentPrompt("")}>Reset</Button>}</div><textarea value={agentPrompt} onChange={e=>setAgentPrompt(e.target.value)} placeholder={PROMPT_PLACEHOLDER} rows={10} className="w-full resize-y rounded-lg border border-kumo-line bg-kumo-recessed px-3 py-2 text-xs font-mono leading-relaxed"/></div>
  <div className="rounded-lg border border-kumo-line bg-kumo-base p-5"><div className="text-sm font-medium mb-3">Email Signature</div><p className="text-xs text-kumo-subtle mb-4">Inserted automatically into new messages, replies and forwards. HTML is supported.</p><label className="flex items-center gap-2 text-sm mb-4"><input type="checkbox" checked={signatureEnabled} onChange={e=>setSignatureEnabled(e.target.checked)}/> Enable signature</label><textarea value={signatureHtml} onChange={e=>setSignatureHtml(e.target.value)} rows={7} disabled={!signatureEnabled} placeholder={DEFAULT_SIGNATURE} className="w-full resize-y rounded-lg border border-kumo-line bg-kumo-recessed px-3 py-2 text-sm font-mono"/><div className="mt-4 flex items-center gap-4"><label className={`inline-flex items-center gap-2 cursor-pointer text-sm rounded-md border border-kumo-line px-3 py-2 ${isUploading?"opacity-50 pointer-events-none":""}`}><ImageIcon size={16}/>{isUploading?"Uploading…":"Upload company logo"}<input type="file" accept="image/png,image/jpeg,image/gif,image/webp" className="hidden" onChange={handleLogo} disabled={!signatureEnabled||isUploading}/></label>{logoUrl&&<div className="flex items-center gap-3"><img src={logoUrl} alt="Signature logo" className="max-h-20 max-w-48 object-contain border rounded p-1"/><Button size="xs" variant="ghost" onClick={()=>void removeLogo()}>Remove</Button></div>}</div><p className="text-xs text-kumo-subtle mt-3">Logo is stored in R2 and sent inline, not as a normal attachment.</p></div>
  <div className="rounded-lg border border-kumo-line bg-kumo-base p-5"><div className="flex items-center gap-2 mb-2"><PaperPlaneTiltIcon size={17}/><div className="text-sm font-medium">Third-party email forwarding</div></div><label className="flex items-center gap-2 text-sm mb-3"><input type="checkbox" checked={forwardEnabled} onChange={e=>setForwardEnabled(e.target.checked)}/> Enable forwarding</label><Input label="Forward to" type="email" value={forwardEmail} onChange={e=>setForwardEmail(e.target.value)} disabled={!forwardEnabled} placeholder="backup@example.com"/><label className="flex items-center gap-2 text-xs text-kumo-subtle mt-3"><input type="checkbox" checked={forwardInternal} onChange={e=>setForwardInternal(e.target.checked)} disabled={!forwardEnabled}/> Also forward internal mail</label></div>
  <div className="rounded-lg border border-kumo-line bg-kumo-base p-5"><div className="flex items-center gap-2 mb-2"><TelegramLogoIcon size={17}/><div className="text-sm font-medium">Telegram notifications</div></div><label className="flex items-center gap-2 text-sm mb-3"><input type="checkbox" checked={telegramEnabled} onChange={e=>setTelegramEnabled(e.target.checked)}/> Enable Telegram notifications</label><div className="space-y-3"><Input label="Bot Token" type="password" value={telegramToken} onChange={e=>setTelegramToken(e.target.value)} disabled={!telegramEnabled}/><Input label="Chat ID" value={telegramChatId} onChange={e=>setTelegramChatId(e.target.value)} disabled={!telegramEnabled}/></div><label className="flex items-center gap-2 text-xs text-kumo-subtle mt-3"><input type="checkbox" checked={telegramInternal} onChange={e=>setTelegramInternal(e.target.checked)} disabled={!telegramEnabled}/> Also notify for internal mail</label></div>
  <div className="flex justify-end"><Button variant="primary" onClick={handleSave} loading={isSaving}>Save Changes</Button></div>
 </div></div>;
}
